<script setup lang="ts">
import { ref } from 'vue';

const showModal = ref(true);
const step = ref(1);

const nextStep = () => {
	if (step.value < 3) {
		step.value += 1;
	}
};

const prevStep = () => {
	if (step.value > 1) {
		step.value -= 1;
	}
};

const closeModal = () => {
	showModal.value = false;
};
</script>

<template>
	<div v-if="showModal" class="modal">
		<div class="modal-content">
			<h2 v-if="step === 1">Welcome to the Homegate Apartment Reviews</h2>
			<div v-if="step === 1">
				Homegate Apartment Reviews is a conceptual project created to showcase
				the potential of a comprehensive apartment reviews application. It's
				designed to help individuals make informed decisions when searching for
				their dream apartment.
				<br />
				<br />
				It's important to clarify that this app is a
				<strong>proof of concept</strong> and <strong>DOES NOT</strong> have any
				real-world implications or intentions of infringing on others data.
			</div>
			<h2 v-if="step === 2">Key Features</h2>
			<div v-if="step === 2">
				<p>
					1. <strong>Apartment Listings</strong>: The app provides a glimpse
					into how real-time apartment data can be displayed. However, it is
					essential to note that the data is sourced solely for illustrative
					purposes and does not constitute actual listings.
				</p>
				<p>
					2. <strong>AI-Generated Reviews</strong>: The reviews you see on this
					platform are generated by artificial intelligence to showcase the
					concept of user reviews. They are entirely fictional and not based on
					any real user experiences.
				</p>
				<p>
					3. <strong>Limited Apartment Availability</strong>: To maintain a
					controlled environment, we've intentionally limited the available
					apartments for review to a predefined set of 10.
				</p>
				<p>
					4. <strong>User Accounts</strong>: The app includes a set of 30 fake
					user accounts tied to the fake reviews. While you can log in as one of
					these users to leave reviews, there is no functionality to register
					new users.
				</p>
			</div>
			<h2 v-if="step === 3">Disclaimer</h2>
			<div v-if="step === 3">
				<p>
					<strong>Data Sources</strong>: The apartment data, including rent
					price, living space, location, number of rooms, description, features,
					availability and images, is obtained from a publicly available website
					and is used only for the purpose of demonstrating the capabilities of
					this application. No data is copied or stored beyond this
					demonstration, and it does not constitute real listings.
				</p>
				<p>
					<strong>Privacy</strong>: No personal data or information is collected
					from users of this application.
				</p>
				<p>
					<strong>Intent</strong>: The sole purpose of this app is to showcase
					my technical skills as a developer and does not intend to deceive or
					misuse data in any way.
				</p>
			</div>
			<div class="modal-buttons">
				<button @click="prevStep" v-if="step > 1">Previous</button>
				<button @click="nextStep" v-if="step < 3">Next</button>
				<button @click="closeModal">Close</button>
			</div>
		</div>
	</div>
</template>

<style scoped>
.modal {
	position: fixed;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	background-color: rgba(0, 0, 0, 0.5);
	display: flex;
	justify-content: center;
	align-items: center;
	z-index: 100;
}

.modal-content {
	position: relative;
	padding: 4rem;
	width: 800px;
	height: 600px;
	display: flex;
	flex-direction: column;
	justify-content: space-between;
	gap: 3rem;
	text-align: left;
	border-radius: 8px;
	background: #1a1a1a;
}

.modal-buttons {
	margin-left: auto;
	height: 50px;
	display: flex;
	gap: 1rem;
}

.modal-buttons button {
	height: 100%;
}

.modal-buttons button:focus {
	border: 1px solid #999;
	outline: none;
}

.modal-buttons button:hover {
	border: 1px solid #e5007d;
	outline: none;
}
</style>
